### ISSUE TITLE
i can't find any method to 

### ISSUE THREAD

**Issue by 108527307** [pkouris/abtextsum#2]
Traceback (most recent call last):
  File "build_dataset.py", line 518, in <module>
    BuildDataset()
  File "build_dataset.py", line 39, in __init__
    param.lines_per_chunk, param.read_lines)
  File "build_dataset.py", line 136, in build_whole_train_dataset_and_dictionary
    num_of_lines = self.num_of_lines_of_file(file=train_article_path)
  File "build_dataset.py", line 77, in num_of_lines_of_file
    with open(file, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/datasets/directorytrain/train_lg100d5gigaword_article.txt'

when i start to run the  'python build_dataset.py -mode train -model lg100d5g'

**Comment by pkouris** [comment]
The file train_lg100d5gigaword_article.txt is the file of articles of the Gigaword dataset that has been generalized by using the LG generalization strategy (see the paper). By running the above command with argument -mode lg100d5, the process requires to take as input the files train_lg100d5gigaword_article.txt and train_lg100d5gigaword_title.txt, because they were used in the experimental procedure of the paper (see readme.md file which describes how to use the generalization strategies). 

Regardless of these specific files, you could build the dataset and train a model by using any pair of files with articles and summaries, respectively. You should slightly change the files build_dataset.py and paths.py to use any pair of files with articles and summaries as input files.  

For more information see the readme.md file of this repository.

I understand that these specific filenames (which was used in the experimental procedure of the paper) restrict the framework of using in more general applications. We aim to simplify the code to be more general for using any dataset filename without restrictions. We will do that as soon as possible.

**Comment by 108527307** [comment]
Thank you very much. I have ran it.
